version: "3.5"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
      - cloudacademylabs
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=tcp://socat:2375
    depends_on:
      - socat
  socat:
    container_name: socat
    #simage: socat-ca:latest
    image: alpine/socat:latest
    networks:
      - cloudacademylabs
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
  postgres:
    container_name: postgres
    #image: postgres-ca:latest
    image: postgres:latest
    networks:
      - cloudacademylabs
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  sonarqube:
    container_name: sonarqube
    #image: sonarqube-ca:latest
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - cloudacademylabs
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres
  artifactory:
    container_name: artifactory
    #image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    image: docker.bintray.io/jfrog/artifactory-oss:6.5.3
    networks:
      - cloudacademylabs
    ports:
      - 8081:8081
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - DB_USER=sonar
      - DB_PASSWORD=sonarpasswd
      # Add extra Java options by uncommenting the following line
      #- EXTRA_JAVA_OPTIONS=-Xmx4g
    depends_on:
      - postgres
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
networks:
  cloudacademylabs:
    name: cloudacademylabs
